warnings_are_errors: false
language: node_js
node_js:
  - '10'
  - node
install:
- yarn global add travis-ci-cloudfront-invalidation
- yarn
script:
- CI=false yarn build
deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_ID
  secret_access_key: $AWS_SECRET_ID
  region: us-west-2
  app: "node-js-app"
  env: "node-js-app-env"
  bucket_name: "elasticbeanstalk-us-west-2-736998360651"
  on:
    branch: s3-elasticbeanstalk-node