warnings_are_errors: false
language: node_js
node_js:
  - '10'
  - node
install:
- npm install
cache:
  directories:
    - node_modules
deploy:
- provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  local_dir: ./
  skip_cleanup: true
  on:
    branch: travis-ci-codedeploy-ec2
  bucket: travis-ci-jonathon
  region: ap-south-1
- provider: codedeploy
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  bucket: travis-ci-jonathon
  key: latest.zip
  bundle_type: zip
  application: Travis-Code-Deploy
  deployment_group: Travis-Code-Deploy-deploy-grp
  region: us-west-2
  on:
    branch: travis-ci-codedeploy-ec2
before_script:
- npm run test    
script:
  - rm -rf node_modules
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip