version: 0.0
os: linux
files:
  - source: /
    destination: /opt/api
hooks:
  BeforeInstall:
    - location: deploy/before_install.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/restart_server.sh
      timeout: 300
      runas: root